# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    echo $PWD
    var=$(pwd)
    echo "$var"
    cd Tutorial2
    make
    bash /build_output/threadTest

  displayName: 'make'
